package catapi

const baseUrl = "https://app.hbooker.com"
const searchBookApiPoint = "/bookcity/get_filter_search_book_list"
const chapterCommandApiPoint = "/chapter/get_chapter_command"
const chapterInfoApiPoint = "/chapter/get_cpt_ifm"
const bookInfoApiPoint = "/book/get_info_by_id"
const catalogNewApiPoint = "/chapter/get_updated_chapter_by_division_new"
const catalogApiPoint = "/book/get_division_list"
const accountInfoApiPoint = "/reader/get_my_info"
const bookshelfListApiPoint = "/bookshelf/get_shelf_list"
const bookshelfBookListApiPoint = "/bookshelf/get_shelf_book_list"
const loginApiPoint = "/signup/login"
const autoRegV2ApiPoint = "/signup/auto_reg_v2"
const useGeetestApiPoint = "/signup/use_geetest"
